# Generated by Django 3.1 on 2020-09-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_itemvalue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvalue',
            name='reason',
            field=models.CharField(choices=[('pu', 'Purchase'), ('mf', 'Manufacturing'), ('rp', 'Repair'), ('uc', 'User correction')], default='pu', max_length=2, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='itemvalue',
            name='status',
            field=models.CharField(choices=[('nd', 'Needs'), ('or', 'Ordered'), ('pa', 'Paid'), ('ow', 'On the way'), ('re', 'Done')], default='nd', max_length=2, verbose_name='Status'),
        ),
    ]
