# Generated by Django 3.1 on 2020-09-07 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0026_auto_20200904_1709'),
        ('purchase', '0005_auto_20200907_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvalue',
            name='assembly_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='value_used_in', to='items.item'),
        ),
        migrations.AlterField(
            model_name='itemvalue',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_value', to='items.item'),
        ),
    ]
