# Generated by Django 3.1 on 2020-09-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_auto_20200907_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvalue',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True, verbose_name='price'),
        ),
    ]
