# Generated by Django 3.1 on 2020-09-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_itemvalue_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemvalue',
            options={'permissions': (('can_order', 'Can order needs'), ('can_pay', 'Can pay ordered'), ('can_deliver', 'Can make delivery'), ('can_done', 'Can accept to warehouse'))},
        ),
    ]
