# Generated by Django 3.1 on 2020-09-11 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_auto_20200907_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='itemvalue',
            name='status',
            field=models.CharField(choices=[('pr', 'Preliminary'), ('nd', 'Needs'), ('or', 'Ordered'), ('pa', 'Paid'), ('ow', 'On the way'), ('dn', 'Done')], default='nd', max_length=2, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_members', to='purchase.staffmember')),
            ],
        ),
    ]
