# Generated by Django 3.1 on 2020-09-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_auto_20200911_0921'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='staffmember',
            constraint=models.UniqueConstraint(fields=('name', 'supervisor'), name='unique_subcategory'),
        ),
    ]
