# Generated by Django 3.1 on 2020-09-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_auto_20200911_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffMember',
        ),
    ]
