# Generated by Django 3.1 on 2020-09-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_delete_staffmember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemvalue',
            options={'ordering': ['-created_at'], 'permissions': (('can_order', 'Can order needs'), ('can_pay', 'Can pay ordered'), ('can_deliver', 'Can make delivery'), ('can_done', 'Can accept to warehouse'))},
        ),
        migrations.AddIndex(
            model_name='itemvalue',
            index=models.Index(fields=['item'], name='purchase_it_item_id_344910_idx'),
        ),
        migrations.AddIndex(
            model_name='itemvalue',
            index=models.Index(fields=['status'], name='purchase_it_status_2f3724_idx'),
        ),
        migrations.AddIndex(
            model_name='itemvalue',
            index=models.Index(fields=['updated_at'], name='purchase_it_updated_03d5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='itemvalue',
            index=models.Index(fields=['reason'], name='purchase_it_reason_b78bfe_idx'),
        ),
    ]
