# Generated by Django 3.1 on 2020-08-25 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=200, unique=True, verbose_name='Part Number')),
                ('collection_name', models.CharField(max_length=200, verbose_name='Collection name')),
                ('item_type', models.CharField(choices=[('co', 'Component'), ('ap', 'Assembly Part'), ('cm', 'Consumables')], default='co', max_length=2, verbose_name='Type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value', models.IntegerField(default=0, verbose_name='value')),
                ('value_units', models.CharField(choices=[('pcs', 'pcs'), ('ml', 'ml'), ('g', 'g'), ('mm', 'mm')], default='pcs', max_length=5, verbose_name='Units')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created_by')),
            ],
        ),
    ]
