# Generated by Django 3.1 on 2020-08-25 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Part Number')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('co', 'Component'), ('ap', 'Assembly Part'), ('cm', 'Consumable')], default='co', max_length=2, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='ItemSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Part Number')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.itemcategory', verbose_name='Category')),
            ],
        ),
    ]
