# Generated by Django 3.1 on 2020-08-25 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200825_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='items.itemsubcategory', verbose_name='Sub Category'),
            preserve_default=False,
        ),
    ]
