# Generated by Django 3.1 on 2020-08-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsubcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Part Number'),
        ),
    ]
