# Generated by Django 3.1 on 2020-08-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20200825_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='subcategory',
        ),
    ]
