# Generated by Django 3.1 on 2020-08-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20200825_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='_price',
        ),
    ]
