# Generated by Django 3.1 on 2020-08-25 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20200825_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='_price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='_price'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='itemsubcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Sub Category name'),
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assembly_part', to='items.item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='items.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='bom',
            field=models.ManyToManyField(related_name='related_to', through='items.BOM', to='items.Item'),
        ),
    ]
