# Generated by Django 3.1 on 2020-08-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_bom_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='position',
            field=models.CharField(default='R1', max_length=200, verbose_name='position'),
            preserve_default=False,
        ),
    ]
