# Generated by Django 3.1 on 2020-08-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_item_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Comment'),
        ),
    ]
