# Generated by Django 3.1 on 2020-08-31 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20200831_1134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemPrice',
        ),
    ]
