# Generated by Django 3.1 on 2020-08-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_delete_itemprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='attributes',
            field=models.JSONField(blank=True, null=True, verbose_name='Attributes'),
        ),
    ]
