# Generated by Django 3.1 on 2020-08-31 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_item_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='collection_name',
        ),
    ]
