# Generated by Django 3.1 on 2020-09-01 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_remove_item_collection_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='value',
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.itemsubcategory', verbose_name='Category'),
        ),
    ]
