# Generated by Django 3.1 on 2020-09-02 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_auto_20200902_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='assembly_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consist_of', to='items.item'),
        ),
    ]
