# Generated by Django 3.1 on 2020-09-11 06:21

from django.db import migrations, models
import django.db.models.deletion
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0026_auto_20200904_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdocfile',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document', to='items.doctype', verbose_name='Document type'),
        ),
        migrations.AlterField(
            model_name='itemdocfile',
            name='document',
            field=models.FileField(max_length=255, upload_to=items.models.get_doc_file_path, verbose_name='Document'),
        ),
    ]
