# Generated by Django 3.1 on 2020-09-11 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0027_auto_20200911_0921'),
        ('purchase', '0011_delete_staffmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsubcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_subcategory', to='items.itemsubcategory'),
        ),
        migrations.AddConstraint(
            model_name='itemsubcategory',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_subcategory'),
        ),
    ]
