# Generated by Django 3.1 on 2020-09-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0029_auto_20200911_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('part_number', 'subcategory__name')},
        ),
        migrations.AlterModelOptions(
            name='itemsubcategory',
            options={'ordering': ['name', 'category__name']},
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['item'], name='items_bom_item_id_d2dfbb_idx'),
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['assembly_part'], name='items_bom_assembl_e2965d_idx'),
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['item', 'assembly_part'], name='items_bom_item_id_74f243_idx'),
        ),
        migrations.AddIndex(
            model_name='doctype',
            index=models.Index(fields=['name'], name='items_docty_name_ad1595_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['part_number'], name='items_item_part_nu_022819_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['comment'], name='items_item_comment_99c42b_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['subcategory'], name='items_item_subcate_d3bb57_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_type'], name='items_item_item_ty_048ead_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['name'], name='items_itemc_name_166b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsubcategory',
            index=models.Index(fields=['name'], name='items_items_name_f403c6_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsubcategory',
            index=models.Index(fields=['parent'], name='items_items_parent__7e9d95_idx'),
        ),
    ]
